### ISSUE TITLE
Display graphs for different time periods

### ISSUE THREAD

**Issue by kloesing** [makepanic/globe#47]
The server-side Globe currently doesn't have graphs for different time periods.  Moving this discussion here from tor-talk@lists.torproject.org.

Option 1: display graphs below each other (like Atlas does).  Not pretty, but maybe the best solution we have without client-side JavaScript.

Option 2: merge all periods into one graph.  I'm actually not sure how this would look like.  Would all data points be on the same x axis?  Then that's going to defeat the purpose of giving higher data resolution for more recent time periods.  Maybe you can explain in more detail?

**Comment by makepanic** [comment]
Option 2 visualized:
![graphs](http://i.imgur.com/syTnJHG.png)
Basically it starts from the smallest period and loops through all of them. Once it is on the edge of the current period it continues with the value from the next, larger period. This way we have the highest resolution for each x axis value.

We could include the graph inside a scrolling div or something.
Because the renderer uses svg the filesize shouldn't increase that much (haven't testet it yet).

If we go with Option 1 I would like to implement the container as described in Option 2. This way we can give the user a bigger graph without losing much space on the page.

What do you think?

**Comment by kloesing** [comment]
Option 2 above has "1 week" written twice, so I guess purple is supposed to be "1 month" and green "3 months".  Still, I'm having difficulties imagining how this is going to work with up to 5 years of data.  If we're displaying 1 week by default, the graph is going to be huge.  And it won't be easy for users to see trends over 5 years if the graph is 250 times as wide as the browser window.

But option 1 with a "scrolling div container" (or however that's called) sounds like a fine plan.  Might be good to add a hint "scroll down for different time periods" or the like, or users won't find the other graphs.

**Comment by makepanic** [comment]
Ok. I guess we should go with 1 svg per period.

I have another question regarding the implementation. 
When rendering the template I would try to include all graphs via (pseudocode):

```
each period in relay.bandwidth.periods
  img(src='/relay/bandwidth/' + relay.hashed_fingerprint + '.svg?period=' + period)
```

This way we can define a period with a url parameter (`/relay/bandwidth/:fingerprint.svg?period=3_days`). 

The problem is that, using a detail document, I don't know what periods are available. To obtain this information the server could use the onionoo api and request weight/bandwidth documents on loading detail documents.

Now when the browser renders the page, it sees the image elements and starts up to 6 requests (3_days - 5_years) for bandwidth, 5 requests (1_week - 5_years) for weights. If we implement a caching mechanism the server can use data provided by the weight/bandwidth requests from the initial detail document request. Without any form of caching the server starts another (maximum) 11 requests to the onionoo api.

Another approach would be to combine all periods into one graph. This results in a single svg that contains all periods but uses only 1 request.

What do you think would be the better implementation to solve this problem?

**Comment by kloesing** [comment]
How about this: whenever the Globe server is asked for a details page, it requests details + bandwidth + weights documents from Onionoo and does not start writing the page before it has all three.  Then it can include only the links for graphs that do exist.  And when the graph requests come in, it already has the bandwidth and weights documents available.

In general, having a separate svg for each graph sounds like the better approach.  But if we can't have that, let's consider a single svg with all graphs as an alternative.

**Comment by makepanic** [comment]
I pushed changes that enable support for displaying all periods on detail pages.
Could you check if the version with wider graphs and scrollbars is ok (i deployed it on heroku)?

**Comment by kloesing** [comment]
Wow, the graph selection part works really well and looks good!  Nice!

The part that is less intuitive is that you need to scroll horizontally to see the full graphs.  At least that's what happens on my 11'' laptop.  Would it be possible to reduce graph width to about 1/3 to 1/4 of the current size?

**Comment by makepanic** [comment]
Ok i reverted the scrolling graphs.

If there's nothing missing I'm going to close this issue.

**Comment by kloesing** [comment]
Looks awesome!  Yes, feel free to close this issue.  Or hey, I can do that, too.  Thanks a lot!  Great stuff!
