### ISSUE TITLE
duplicate nodes

### ISSUE THREAD

**Issue by poiuty** [makepanic/globe#49]
I have 5 nodes, but globe show 7
https://globe.torproject.org/#/search/query=poiuty

**Comment by ghost** [comment]
Actually this is correct behavior. Your poiuty2 und poiuty3 have changed its fingerprint at some point in time. Have you maybe started it manually and switched to the init-script after a while? Because this is what happened to me.
In about a week the offline relays should be gone.

BTW: You forgot to set your Family. Please add it.

**Comment by poiuty** [comment]
NodeFamily ACA73F5072466385E10B61078276C352C57223BB,A95EA1822AEC5E909530AD2D33C1E08500B10D10,5155AD17D4AD03146F714272ABE09E2C056DAD5A,C81D841E6B3EB2AEE82825C9D2B062FCD2C728A9,5A898F5F1B5C5767A4C90A64EFAE4FD2619236C0

right?

or 
MyFamily $ACA73F5072466385E10B61078276C352C57223BB,$A95EA1822AEC5E909530AD2D33C1E08500B10D10,$5155AD17D4AD03146F714272ABE09E2C056DAD5A,$C81D841E6B3EB2AEE82825C9D2B062FCD2C728A9,$5A898F5F1B5C5767A4C90A64EFAE4FD2619236C0

**Comment by ghost** [comment]
I use the nicknames in my torrc.
Otherwise: ‚Be sure to prefix the digest strings with a dollar sign ('$') so that the digest is not confused with a nickname in the config file.‘ https://www.torproject.org/docs/faq.html.en#MultipleRelays

**Comment by poiuty** [comment]
Thx. Family Members - works.
